# Generated by Django 6.0.4 on 2026-05-12 23:31

import django.db.models.deletion
from django.db import migrations, models


def asignar_tienda_principal(apps, schema_editor):
    Tienda = apps.get_model('configuraciones', 'Tienda')
    MovimientoInventario = apps.get_model('inventario', 'MovimientoInventario')
    HistorialPrecio = apps.get_model('inventario', 'HistorialPrecio')

    tienda = Tienda.objects.filter(codigo='PRINCIPAL').first()
    if not tienda:
        tienda = Tienda.objects.create(codigo='PRINCIPAL', nombre='Sucursal Principal', activa=True)

    MovimientoInventario.objects.filter(tienda__isnull=True).update(tienda=tienda)
    HistorialPrecio.objects.filter(tienda__isnull=True).update(tienda=tienda)


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0005_tienda_puntoventa_perfilusuario_and_more'),
        ('inventario', '0004_producto_activo_historialprecio'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialprecio',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones.tienda'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones.tienda'),
        ),
        migrations.RunPython(asignar_tienda_principal, migrations.RunPython.noop),
    ]
