# Generated by Django 6.0.4 on 2026-05-18 19:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuraciones', '0007_alter_configuracionsistema_options'),
        ('inventario', '0005_historialprecio_tienda_movimientoinventario_tienda'),
        ('ventas', '0005_sesioncaja_punto_venta_sesioncaja_tienda_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permitir_para_llevar', models.BooleanField(default=True)),
                ('usa_estaciones', models.BooleanField(default=False)),
                ('reintegrar_pendiente', models.BooleanField(default=True)),
                ('reintegrar_preparando', models.BooleanField(default=False)),
                ('reintegrar_listo', models.BooleanField(default=False)),
                ('requerir_motivo_cancelacion_enviados', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstacionPreparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('zona', models.CharField(blank=True, max_length=80)),
                ('capacidad', models.PositiveIntegerField(default=4)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['zona', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MESA', 'Mesa'), ('PARA_LLEVAR', 'Para llevar')], default='MESA', max_length=14)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_COCINA', 'En cocina'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado'), ('COBRADO', 'Cobrado'), ('CANCELADO', 'Cancelado')], default='ABIERTO', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('cobrado_en', models.DateTimeField(blank=True, null=True)),
                ('cancelado_en', models.DateTimeField(blank=True, null=True)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='restaurante.mesa')),
                ('mesero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_restaurante', to=settings.AUTH_USER_MODEL)),
                ('tienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuraciones.tienda')),
                ('venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_restaurante', to='ventas.venta')),
            ],
            options={
                'ordering': ['-actualizado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente'), ('PREPARANDO', 'Preparando'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cancelado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('reintegro_stock', models.BooleanField(default=False)),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='restaurante.estacionpreparacion')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurante.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_restaurante', to='inventario.producto')),
            ],
            options={
                'ordering': ['creado_en', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='restaurante.pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='restaurante.pedidoitem')),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductoPreparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviar_a_kds', models.BooleanField(default=True)),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='restaurante.estacionpreparacion')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preparacion', to='inventario.producto')),
            ],
        ),
    ]
