# Generated by Django 6.0.4 on 2026-04-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(default='Mi Negocio', max_length=100)),
                ('pagina_inicio', models.CharField(choices=[('POS', 'Punto de Venta'), ('DASHBOARD', 'Dashboard de Ventas')], default='POS', max_length=20)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
            },
        ),
    ]
