# Generated by Django 6.0.4 on 2026-04-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionsistema',
            options={'permissions': [('acceder_ventas', 'Módulo de Ventas: Acceso al Punto de Venta y Cobro'), ('acceder_inventario', 'Módulo de Inventario: Gestión de Productos y Categorías'), ('acceder_configuraciones', 'Módulo de Configuración: Usuarios, Roles y Ajustes')], 'verbose_name': 'Configuración del Sistema'},
        ),
    ]
