# Generated by Django 6.0.4 on 2026-04-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0002_alter_configuracionsistema_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='pagina_inicio',
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Dirección que aparecerá en el ticket', max_length=255, null=True),
        ),
    ]
