# Generated by Django 6.0.4 on 2026-05-12 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def crear_tienda_principal(apps, schema_editor):
    Tienda = apps.get_model('configuraciones', 'Tienda')
    PuntoVenta = apps.get_model('configuraciones', 'PuntoVenta')
    PerfilUsuario = apps.get_model('configuraciones', 'PerfilUsuario')
    User = apps.get_model('auth', 'User')

    tienda, _ = Tienda.objects.get_or_create(
        codigo='PRINCIPAL',
        defaults={'nombre': 'Sucursal Principal', 'direccion': '', 'telefono': '', 'activa': True},
    )
    punto, _ = PuntoVenta.objects.get_or_create(
        tienda=tienda,
        codigo='CAJA-1',
        defaults={'nombre': 'Caja 1', 'activo': True},
    )

    for user in User.objects.all():
        PerfilUsuario.objects.get_or_create(
            usuario=user,
            defaults={
                'tienda': tienda,
                'punto_venta': punto,
                'puede_ver_todas_las_tiendas': user.is_superuser,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0004_renombrar_permiso_sistema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('codigo', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_venta', to='configuraciones.tienda')),
            ],
            options={
                'ordering': ['tienda__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_ver_todas_las_tiendas', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('punto_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='configuraciones.puntoventa')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='configuraciones.tienda')),
            ],
        ),
        migrations.AddConstraint(
            model_name='puntoventa',
            constraint=models.UniqueConstraint(fields=('tienda', 'codigo'), name='punto_venta_codigo_unico_por_tienda'),
        ),
        migrations.RunPython(crear_tienda_principal, migrations.RunPython.noop),
    ]
