# Generated by Django 6.0.4 on 2026-05-13 17:38

from django.db import migrations


PERMISOS_GRANULARES = [
    ('operar_pos', 'Ventas: Operar POS y cobrar'),
    ('abrir_cerrar_caja', 'Ventas: Abrir y cerrar caja'),
    ('cancelar_ventas', 'Ventas: Cancelar tickets'),
    ('ver_historial_ventas', 'Ventas: Ver historial y reimprimir tickets'),
    ('ver_estadisticas', 'Ventas: Ver estadísticas'),
    ('ver_turnos', 'Ventas: Ver turnos y cortes'),
    ('ver_inventario', 'Inventario: Ver productos y movimientos'),
    ('editar_productos', 'Inventario: Crear y editar productos/categorías'),
    ('ajustar_stock', 'Inventario: Ajustar stock y registrar entradas'),
    ('editar_precios', 'Inventario: Editar precios'),
    ('importar_exportar_inventario', 'Inventario: Importar y exportar catálogo'),
    ('imprimir_etiquetas', 'Inventario: Imprimir etiquetas'),
    ('gestionar_usuarios', 'Sistema: Gestionar usuarios'),
    ('gestionar_roles', 'Sistema: Gestionar roles'),
    ('gestionar_tiendas', 'Sistema: Gestionar tiendas y cajas'),
    ('editar_preferencias', 'Sistema: Editar preferencias'),
]

PERMISOS_LEGACY_A_GRANULARES = {
    'acceder_ventas': [
        'operar_pos',
        'abrir_cerrar_caja',
        'cancelar_ventas',
        'ver_historial_ventas',
        'ver_estadisticas',
        'ver_turnos',
    ],
    'acceder_inventario': [
        'ver_inventario',
        'editar_productos',
        'ajustar_stock',
        'editar_precios',
        'importar_exportar_inventario',
        'imprimir_etiquetas',
    ],
    'acceder_configuraciones': [
        'gestionar_usuarios',
        'gestionar_roles',
        'gestionar_tiendas',
        'editar_preferencias',
    ],
}


def crear_y_migrar_permisos_granulares(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Group = apps.get_model('auth', 'Group')
    User = apps.get_model('auth', 'User')

    content_type, _ = ContentType.objects.get_or_create(
        app_label='configuraciones',
        model='configuracionsistema',
    )

    permisos = {}
    for codename, name in PERMISOS_GRANULARES:
        permiso, created = Permission.objects.get_or_create(
            content_type=content_type,
            codename=codename,
            defaults={'name': name},
        )
        if not created and permiso.name != name:
            permiso.name = name
            permiso.save(update_fields=['name'])
        permisos[codename] = permiso

    for codename_legacy, codenames_granulares in PERMISOS_LEGACY_A_GRANULARES.items():
        permiso_legacy = Permission.objects.filter(
            content_type=content_type,
            codename=codename_legacy,
        ).first()
        if permiso_legacy is None:
            continue

        permisos_nuevos = [permisos[codename] for codename in codenames_granulares]
        for grupo in Group.objects.filter(permissions=permiso_legacy).distinct():
            grupo.permissions.add(*permisos_nuevos)
        for usuario in User.objects.filter(user_permissions=permiso_legacy).distinct():
            usuario.user_permissions.add(*permisos_nuevos)


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0005_tienda_puntoventa_perfilusuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionsistema',
            options={'permissions': [('acceder_ventas', 'Módulo de Ventas: Acceso al Punto de Venta y Cobro'), ('acceder_inventario', 'Módulo de Inventario: Gestión de Productos y Categorías'), ('acceder_configuraciones', 'Módulo de Sistema: Usuarios, Roles y Preferencias'), ('operar_pos', 'Ventas: Operar POS y cobrar'), ('abrir_cerrar_caja', 'Ventas: Abrir y cerrar caja'), ('cancelar_ventas', 'Ventas: Cancelar tickets'), ('ver_historial_ventas', 'Ventas: Ver historial y reimprimir tickets'), ('ver_estadisticas', 'Ventas: Ver estadísticas'), ('ver_turnos', 'Ventas: Ver turnos y cortes'), ('ver_inventario', 'Inventario: Ver productos y movimientos'), ('editar_productos', 'Inventario: Crear y editar productos/categorías'), ('ajustar_stock', 'Inventario: Ajustar stock y registrar entradas'), ('editar_precios', 'Inventario: Editar precios'), ('importar_exportar_inventario', 'Inventario: Importar y exportar catálogo'), ('imprimir_etiquetas', 'Inventario: Imprimir etiquetas'), ('gestionar_usuarios', 'Sistema: Gestionar usuarios'), ('gestionar_roles', 'Sistema: Gestionar roles'), ('gestionar_tiendas', 'Sistema: Gestionar tiendas y cajas'), ('editar_preferencias', 'Sistema: Editar preferencias')], 'verbose_name': 'Configuración del Sistema'},
        ),
        migrations.RunPython(crear_y_migrar_permisos_granulares, migrations.RunPython.noop),
    ]
