# Generated by Django 6.0.4 on 2026-05-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0006_alter_configuracionsistema_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionsistema',
            options={'permissions': [('acceder_ventas', 'Módulo de Ventas: Acceso al Punto de Venta y Cobro'), ('acceder_inventario', 'Módulo de Inventario: Gestión de Productos y Categorías'), ('acceder_restaurante', 'Módulo de Restaurante: Comandas y cocina'), ('acceder_configuraciones', 'Módulo de Sistema: Usuarios, Roles y Preferencias'), ('operar_pos', 'Ventas: Operar POS y cobrar'), ('abrir_cerrar_caja', 'Ventas: Abrir y cerrar caja'), ('cancelar_ventas', 'Ventas: Cancelar tickets'), ('ver_historial_ventas', 'Ventas: Ver historial y reimprimir tickets'), ('ver_estadisticas', 'Ventas: Ver estadísticas'), ('ver_turnos', 'Ventas: Ver turnos y cortes'), ('ver_inventario', 'Inventario: Ver productos y movimientos'), ('editar_productos', 'Inventario: Crear y editar productos/categorías'), ('ajustar_stock', 'Inventario: Ajustar stock y registrar entradas'), ('editar_precios', 'Inventario: Editar precios'), ('importar_exportar_inventario', 'Inventario: Importar y exportar catálogo'), ('imprimir_etiquetas', 'Inventario: Imprimir etiquetas'), ('operar_restaurante', 'Restaurante: Abrir comandas, enviar a cocina y cobrar'), ('operar_kds', 'Restaurante: Operar pantalla de cocina'), ('configurar_restaurante', 'Restaurante: Configurar mesas y estaciones'), ('gestionar_usuarios', 'Sistema: Gestionar usuarios'), ('gestionar_roles', 'Sistema: Gestionar roles'), ('gestionar_tiendas', 'Sistema: Gestionar tiendas y cajas'), ('editar_preferencias', 'Sistema: Editar preferencias')], 'verbose_name': 'Configuración del Sistema'},
        ),
    ]
