# Generated by Django 6.0.4 on 2026-04-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cambio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='pago_recibido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
