# Generated by Django 6.0.4 on 2026-05-12 23:31

import django.db.models.deletion
from django.db import migrations, models


def asignar_tienda_principal(apps, schema_editor):
    Tienda = apps.get_model('configuraciones', 'Tienda')
    PuntoVenta = apps.get_model('configuraciones', 'PuntoVenta')
    SesionCaja = apps.get_model('ventas', 'SesionCaja')
    Venta = apps.get_model('ventas', 'Venta')

    tienda = Tienda.objects.filter(codigo='PRINCIPAL').first()
    if not tienda:
        tienda = Tienda.objects.create(codigo='PRINCIPAL', nombre='Sucursal Principal', activa=True)
    punto = PuntoVenta.objects.filter(tienda=tienda, codigo='CAJA-1').first()
    if not punto:
        punto = PuntoVenta.objects.create(tienda=tienda, codigo='CAJA-1', nombre='Caja 1', activo=True)

    SesionCaja.objects.filter(tienda__isnull=True).update(tienda=tienda, punto_venta=punto)
    Venta.objects.filter(tienda__isnull=True).update(tienda=tienda)


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0005_tienda_puntoventa_perfilusuario_and_more'),
        ('ventas', '0004_venta_cancelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesioncaja',
            name='punto_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones.puntoventa'),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuraciones.tienda'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuraciones.tienda'),
        ),
        migrations.RunPython(asignar_tienda_principal, migrations.RunPython.noop),
    ]
