# Generated by Django 6.0.4 on 2026-05-18 22:23

import django.db.models.deletion
from django.db import migrations, models


def backfill_pagos_venta(apps, schema_editor):
    Venta = apps.get_model('ventas', 'Venta')
    PagoVenta = apps.get_model('ventas', 'PagoVenta')
    metodos_detalle = {'EFE', 'TAR', 'TRA'}

    for venta in Venta.objects.all().iterator():
        venta.subtotal = venta.total
        venta.propina = 0
        venta.porcentaje_propina = 0
        venta.save(update_fields=['subtotal', 'propina', 'porcentaje_propina'])

        if venta.metodo_pago in metodos_detalle and venta.total > 0:
            PagoVenta.objects.get_or_create(
                venta=venta,
                metodo_pago=venta.metodo_pago,
                defaults={'monto': venta.total},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_sesioncaja_punto_venta_sesioncaja_tienda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='porcentaje_propina',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='venta',
            name='propina',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFE', 'Efectivo'), ('TAR', 'Tarjeta'), ('TRA', 'Transferencia'), ('MIX', 'Mixto')], default='EFE', max_length=3),
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('EFE', 'Efectivo'), ('TAR', 'Tarjeta'), ('TRA', 'Transferencia')], max_length=3)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.venta')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(backfill_pagos_venta, migrations.RunPython.noop),
    ]
